spring:
  application:
    name: shop

  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    mode: HTML
    cache: false
    check-template-location: true
    enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://shoppingmall.mysql.database.azure.com/shop
    username: username of mysql
    password: password of mysql

  jpa:
    # JPA 문법쓸 때, SQL 따로 출력 여부
    properties:
      hibernate:
        format_sql: true
        show_sql: true

    # 테이블 생성 자동 여부
    hibernate:
      ddl-auto: update
    open-in-view: false

  # DB에 세션 데이터 저장
  session:
    jdbc:
      initialize-schema: always

  cloud:
    aws:
      credentials:
        access-key: bucket access key
        secret-key: bucket secret key
      region:
        static: ap-northeast-2
      # custom aws property
      s3:
        bucket: cycotestspringmall

server:
  servlet:
    session:
      timeout: 5m
      cookie:
        max-age: 5m
  port: 8080

logging:
  level:
    root: INFO
    com.personal.shop: DEBUG
    com.personal.shop.controller: TRACE
    com.personal.shop.service: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO
    com.amazons: DEBUG
    software.amazon.awssdk: DEBUG
