spring:
  profiles:
    active: dev

  config:
    import: optional:file:.env.dev[.properties]

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false
    check-template-location: true
    enabled: true
    encoding: UTF-8

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false

  session:
    jdbc:
      initialize-schema: always

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ap-northeast-2
      s3:
        bucket: ctspringmall

server:
  servlet:
    session:
      timeout: 30m
      cookie:
        max-age: 30m
  port: 5000



management:
  endpoints:
    enabled-by-default: false
    jmx:
      exposure:
        exclude: "*"
        include: info, health
    web:
      base-path: /actuator/appHealth
      exposure:
        include: "*"
  info:
    os:
      enabled: true
    java:
      enabled: true
    env:
      enabled: true


logging:
  level:
    root: INFO
    com.personal.shop: DEBUG
    org.springframework.security: DEBUG
    org.hibernate: INFO
    com.amazons: DEBUG
    software.amazon.awssdk: DEBUG