spring:
  application:
    name: shop

  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    mode: HTML5
    cache: false
    check-template-location: true
    enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://shoppingmall.mysql.database.azure.com/shop
    username: cycoTest
    password: 9125Tkdehchemd!

  jpa:
    # JPA 문법쓸 때, SQL 따로 출력 여부
    properties:
      hibernate:
        format_sql: true
        show_sql: true

    # 테이블 생성 자동 여부
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

  # DB에 세션 데이터 저장
  session:
    jdbc:
      initialize-schema: always

server:
  servlet:
    session:
      timeout: 5m
      cookie:
        max-age: 5m